void main() throws IOException {
    System.out.println("Map Collect");
    new Map_Collect();
    System.out.println("Reduce");
    new Reduce();
    System.out.println("Parallel");
    new Parallel();
    System.out.println("InetAddress");
    new InetAddressMethod();
    System.out.println("InputStreamReader");
    new InputStreamReaderMethod();
    System.out.println("RandomStreamPrediction");
    new RandomStreamPrediction();
    System.out.println("Adjacency Lists");
    new AdjacencyLists();
    System.out.println("User Input Recognition");
    new UserInputRecognition();
    System.out.println("Adjacency Matrix");
    new AdjacencyMatrix();
    System.out.println("HashTable 1");
    new HashTable1();
    System.out.println("Merge Sort 1");
    new MergeSort1();
    System.out.println("Recursion");
    new Recursion();
    System.out.println("Selection Sort 1");
    new SelectionSort1();
    System.out.println("InsertionSort 1");
    new InsertionSort1();
    System.out.println("Bubble Sort 1");
    new BubbleSort1();
    System.out.println("Interpolation Search 1");
    new InterpolationSearch1();
    System.out.println("Binary Search 1");
    new BinarySearch1();
    System.out.println("Linear Search 1");
    new LinearSearch1();
    System.out.println("Linked List VS ArrayList");
    new LinkedListVSArrayList();
}